logging:
  level:
    com.nea.patient.access.portal.backend: INFO
    org.springframework: INFO
    org.apache.http: INFO
    org.hibernate.SQL: INFO
    org.hibernate: INFO
  file:
    path: logs
    name: logs/patient-portal-backend-api.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: access-logs
    basedir: logs

spring:
  application:
    name: patient-portal-backend-api
  mvc:
    format:
      date: dd-MM-yyyy
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  h2:
    console:
      enabled: true # Tells the Spring to start H2 Database administration tool and you can access this tool on the browser: http://localhost:8080/h2-console
      path: /h2-ui # Default url http://localhost:8080/h2-console will change to http://localhost:8080/h2-ui

#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.generate-ddl=true

decorator:
  datasource:
    flexy-pool:
      acquiring-strategy:
        increment-pool:
          # Increments pool size if connection acquire request has timed out
          max-overflow-pool-size: 50
          timeout-millis: 500
        retry:
          # Retries on getting connection
          attempts: 5
      threshold:
        connection:
          # Enable logging and publishing ConnectionLeaseTimeThresholdExceededEvent when a connection lease has exceeded the given time threshold
          lease: 20000
          # Enable logging and publishing ConnectionAcquireTimeThresholdExceededEvent when a connection acquire request has timed out
          acquire: 120000
      metrics:
        reporter:
          jmx:
            enabled: true
          log:
            millis: 86400000 # Every 24 hours